---
platform: linux
image: docker:///cloudfoundry/bosh-lite-ci

inputs:
  - name: stemcell
  - name: bosh-softlayer-tools
    path: gopath/src/github.com/cloudfoundry-community/bosh-softlayer-tools

run:
  path: gopath/src/github.com/cloudfoundry-community/bosh-softlayer-tools/ci/tasks/upgrade-stemcell.sh
params:
  BLUEMIX_DIRECTOR_IP:        replace-me
  BOSH_CLI:                   replace-me
  BOSH_CLI_PASSWORD:          replace-me