---
platform: linux
image: docker:///boshcpi/azure-cpi-release

inputs:
- name: director-artifacts
- name: bosh-softlayer-tools
- name: cf-template

run:
  path: bosh-softlayer-tools/ci/tasks/create-env-automation/deploy-cf.sh

outputs:
- name: cf-artifacts
- name: deploy-status

params:
  deploy_name:                          replace-me
  director_ip:                          replace-me
  director_pub_ip:                      replace-me
  data_center_name:                     replace-me
  private_vlan_id:                      replace-me
  public_vlan_id:                       replace-me
  stemcell:                             replace-me
  base_stemcell_version:                replace-me
  update_stemcell_version:				replace-me
  cf_release:                           replace-me
  cf_release_version:                   replace-me
  cf_services_release:                  replace-me
  cf_services_release_version:          replace-me
  cf_services_contrib_release:          replace-me
  cf_services_contrib_release_version:  replace-me
