---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: zhanggongsw/bosh

inputs:
  - name: version
  - name: bosh-softlayer-tools
    path: gopath/src/github.com/cloudfoundry-community/bosh-softlayer-tools
outputs:
  - name: stemcell-image
run:
  path: gopath/src/github.com/cloudfoundry-community/bosh-softlayer-tools/ci/tasks/import-stemcell
params:
  SL_USERNAME:                replace-me
  SL_API_KEY:                 replace-me
