---
platform: linux
image: docker:///boshcpi/azure-cpi-release

inputs:
- name: bosh-softlayer-tools
- name: cf-artifacts-comm
  path: cf-artifacts

run:
  path: bosh-softlayer-tools/ci/softlayer_ng/tasks/verify-cf.sh

params:
  CF_USERNAME: 		replace-me
  CF_PASSWORD: 		replace-me
  APP_API: 			  replace-me
